Lor 101: Fix new application form issues
karan316/EasyLOR pull request #66
Opened 2021-07-31 17:11 UTC by sarthakagrawal927

Check jira for comments

2021-08-05 08:56 UTC, karan316 requested changes

2021-08-05 08:56 UTC, karan316 commented on client/components/modal/index.tsx
> +	let dateField = date.toLocaleDateString() === "01/01/1970" ? "No date selected" : date.toLocaleDateString();
Do something similar when the application is being submitted as well. If the date is the default one, send the dueDate as null or don't send at all. Right now, the due date being sent is 01/01/1970 if no date is selected

2021-08-05 08:56 UTC, karan316 commented on client/lib/newApplication/hooks.tsx
> +	function FileNameWatch({ control }) {
instead of this, use useWatch with useEffect. That's a better way instead of defining a functional component inside hooks. Check the register hooks [file](https://github.com/karan316/EasyLOR/blob/develop/client/lib/register/hooks.tsx) line 111 onwards. 
If it doesn't work then leave it as it is.

2021-08-05 08:56 UTC, karan316 commented on client/components/DatePicker/index.tsx
> +			{startDate && <DeleteIcon onClick={clearDate} w={5} h={5} color="blue" />}
make the color red and set cursor: pointer

2021-08-05 11:09 UTC, sarthakagrawal927 commented on client/lib/newApplication/hooks.tsx
> +	function FileNameWatch({ control }) {
I tried something similar, it was giving too many rerenders error. 
Right now it is just in index.tsx file

2021-08-05 11:15 UTC, sarthakagrawal927 commented on client/components/modal/index.tsx
> +	let dateField = date.toLocaleDateString() === "01/01/1970" ? "No date selected" : date.toLocaleDateString();
In db there are NULL entries with date, I'll reconfirm

2021-08-05 11:18 UTC, sarthakagrawal927 commented on client/components/modal/index.tsx
> +	let dateField = date.toLocaleDateString() === "01/01/1970" ? "No date selected" : date.toLocaleDateString();
It is NULL in db, need to change in dashboard

2021-08-06 08:30 UTC, karan316 approved these changes

2021-08-06 08:31 UTC, merged